# Generated by Django 3.2 on 2021-06-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210603_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='fabric_id',
            new_name='fabric',
        ),
    ]
