# Generated by Django 3.2 on 2021-06-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_fabric_id_cloth_fabric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cloth_name',
            new_name='cloth_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fabric_name',
            new_name='fabric_id',
        ),
    ]
