# Generated by Django 3.2 on 2021-06-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210605_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cloth_id',
            new_name='cloth',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fabric_id',
            new_name='fabric',
        ),
    ]
