# Generated by Django 3.2 on 2021-06-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210605_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cloth',
            new_name='cloth_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fabric',
            new_name='fabric_id',
        ),
    ]
