# Generated by Django 3.2 on 2021-06-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210605_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cloth_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.cloth'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.fabric'),
        ),
    ]
